# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d211899df1a27cde4a63010c52f45087522d34a209e7d0fd0218e15dac603cf445e5c034eadd1de747f4090f6d414bdd665d93d64d2e4453a33828ee247ce11

test:
  secret_key_base: 1dc109c86e1394451039fae34494df9c2ebbb274ff29beac33746993d485deb775386db87740354672f1d2d2a861682398cd1e7ea68b40cd1cecc90e70fbb19f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
